[package]
name = "nom_sql"
version = "0.0.1"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
nom = { version = "4.0.0-alpha2", features = ["verbose-errors"] }
